package com.fitnessapp.model;

import jakarta.persistence.*;

@Entity
@Table(name = "routines")
public class Routine {

    @Id // autogenerated
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;// for bigger range int =32bit long =64bit and postgreSQL ->bigserial 64bit

    @Column(name = "routine_name", nullable = false) // routine must have name?
    private String routineName;

    @ManyToOne // one user can have many routines (legday, pushday, pullday)
    /*
     * From a Routine -> get the owning User
     * From a user -> get all Routines
     */
    @JoinColumn(name = "user_foreign_key", nullable = false) // foreign key column in "routines" table
    /*
     * in routines table, create a column called user_id that stores the foreign key
     * (the ID of
     * user who owns this routine)
     */
    private User user;

    public Routine() {
    }

    public Routine(String routineName, User user) {
        this.routineName = routineName;
        this.user = user;
    }

    // getter
    public String getRoutineName() {
        return this.routineName;
    }

    public User getUser() {
        return this.user;
    }

    public Long getId() {
        return this.id;
    }

    // setter
    public void setUser(User user) {
        this.user = user;
    }

    public void setRoutineName(String routineName) {
        this.routineName = routineName;
    }

    @Override
    public String toString() {
        return "Routine{" +
                "id=" + id +
                ", routineName='" + routineName + '\'' +
                '}';
    }
}
